-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 20:14:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` CHAR(20) NOT NULL,
  `userpass` CHAR(22) NOT NULL,
  `email` CHAR(45) NOT NULL,
  `birthday` INT NOT NULL,
  `permissions` INT NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `name` INT NOT NULL,
  `devices` INT NOT NULL,
  `brandcol` VARCHAR(45) NULL,
  `user_username` CHAR(20) NOT NULL,
  PRIMARY KEY (`name`, `user_username`),
  INDEX `fk_brand_user1_idx` (`user_username` ASC) VISIBLE,
  CONSTRAINT `fk_brand_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`phone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `model` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `release_date` INT ZEROFILL NOT NULL,
  `brand_name` INT NOT NULL,
  PRIMARY KEY (`model`, `brand_name`),
  INDEX `fk_phone_brand_idx` (`brand_name` ASC) VISIBLE,
  CONSTRAINT `fk_phone_brand`
    FOREIGN KEY (`brand_name`)
    REFERENCES `mydb`.`brand` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone_specs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`phone_specs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`phone_specs` (
  `phone_specs` VARCHAR(45) NOT NULL,
  `cam_1` TEXT(45) NOT NULL,
  `cam_2` TEXT(45) NOT NULL,
  `cam_3` TEXT(80) NULL,
  `cam_4` TEXT(45) NULL,
  `cam_front` TEXT(45) NOT NULL,
  `chipset` TEXT(45) NOT NULL,
  `display_tec` TEXT(10) NOT NULL,
  `display_ppp` INT NOT NULL,
  `display_inch` FLOAT NOT NULL,
  `display_freq` INT NOT NULL,
  `batery` INT NOT NULL,
  `charge` INT NOT NULL,
  `os` TEXT(20) NOT NULL,
  `ram` INT NOT NULL,
  `storage` INT NOT NULL,
  `dimensions` TEXT(45) NOT NULL,
  `weight` INT NOT NULL,
  `video_specs` TEXT(45) NOT NULL,
  `5G` BINARY(2) NOT NULL,
  `calification` FLOAT NOT NULL,
  `cal_pri_qua` FLOAT NOT NULL,
  `phone_model` VARCHAR(45) NOT NULL,
  `phone_brand_name` INT NOT NULL,
  PRIMARY KEY (`phone_specs`, `phone_model`, `phone_brand_name`),
  UNIQUE INDEX `phone_specscol1_UNIQUE` (`phone_specs` ASC) VISIBLE,
  INDEX `fk_phone_specs_phone1_idx` (`phone_model` ASC, `phone_brand_name` ASC) VISIBLE,
  CONSTRAINT `fk_phone_specs_phone1`
    FOREIGN KEY (`phone_model` , `phone_brand_name`)
    REFERENCES `mydb`.`phone` (`model` , `brand_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`watch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`watch` ;

CREATE TABLE IF NOT EXISTS `mydb`.`watch` (
  `model` TEXT(45) NOT NULL,
  `code` TEXT(45) NOT NULL,
  `age` INT NULL AUTO_INCREMENT,
  `release_date` DATE NOT NULL,
  `brand_name` INT NOT NULL,
  `brand_user_username` CHAR(20) NOT NULL,
  PRIMARY KEY (`model`, `brand_name`, `brand_user_username`),
  UNIQUE INDEX `release_date_UNIQUE` (`release_date` ASC) VISIBLE,
  INDEX `fk_watch_brand1_idx` (`brand_name` ASC, `brand_user_username` ASC) VISIBLE,
  CONSTRAINT `fk_watch_brand1`
    FOREIGN KEY (`brand_name` , `brand_user_username`)
    REFERENCES `mydb`.`brand` (`name` , `user_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone_specs_copy1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`phone_specs_copy1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`phone_specs_copy1` (
  `phone_specs` VARCHAR(45) NOT NULL,
  `chipset` TEXT(45) NOT NULL,
  `display_tec` TEXT(10) NOT NULL,
  `display_ppp` INT NOT NULL,
  `display_inch` FLOAT NOT NULL,
  `batery` INT NOT NULL,
  `os` TEXT(20) NOT NULL,
  `ram` INT NOT NULL,
  `storage` INT NOT NULL,
  `dimensions` TEXT(45) NOT NULL,
  `weight` INT NOT NULL,
  `SIM` BINARY(2) NOT NULL,
  `calification` FLOAT NOT NULL,
  `cal_pri_qua` FLOAT NOT NULL,
  `watch_model` TEXT(45) NOT NULL,
  `watch_brand_name` INT NOT NULL,
  `watch_brand_user_username` CHAR(20) NOT NULL,
  PRIMARY KEY (`phone_specs`, `watch_model`, `watch_brand_name`, `watch_brand_user_username`),
  UNIQUE INDEX `phone_specscol1_UNIQUE` (`phone_specs` ASC) VISIBLE,
  INDEX `fk_phone_specs_copy1_watch1_idx` (`watch_model` ASC, `watch_brand_name` ASC, `watch_brand_user_username` ASC) VISIBLE,
  CONSTRAINT `fk_phone_specs_copy1_watch1`
    FOREIGN KEY (`watch_model` , `watch_brand_name` , `watch_brand_user_username`)
    REFERENCES `mydb`.`watch` (`model` , `brand_name` , `brand_user_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
